---
title: "GTEx blood + sorted immune cells"
author: "Kushal K Dey"
date: "9/1/2017"
output: html_document
---

We apply classtpx on the GTEx blood samples (bulk) with the sorted cells information obtained
from 10X Genomics.

## GTEx expression processing 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(plyr)
library(classtpx)
library(CountClust)
library(maptpx)
library(ggplot2)
library(MAST)
library(GSEABase)
library(Seurat)
library(data.table)
```

```{r message = FALSE, warning=FALSE}
gtex_expr <- fread("../data/cis_gene_expression.txt")
```

```{r}
mat1 <- as.matrix(gtex_expr[, -(1:2)])
```

```{r}
mat <- apply(mat1, 2, function(x) return(rbinom(dim(gtex_expr)[1], x, 1e-05)))
```

```{r}
samples_id <- read.table("../data/samples_id.txt")
tissue_names <- samples_id[,2]
table(tissue_names)
```

```{r}
idx1 <- which(tissue_names == "Blood")
mat2 <- mat[, idx1]
```


```{r}
gene_names <- as.character(read.table("../data/gene_names_GTEX_V6.txt")[,1])
gene_names_1 <- as.character(sapply(gene_names, function(x) return(strsplit(x, "[.]")[[1]][1])))
```

We convert these ensembl IDs to gene names.

```{r}
out <- mygene::queryMany(gene_names_1,  scopes="ensembl.gene", fields=c("symbol", "ensembl.gene"), species="human");
```

```{r}
idx2 <- match(out$query, gene_names_1)
gene_names_2 <- out$symbol[idx2]
```

```{r}
data_build <- t(mat2)
colnames(data_build) <- gene_names_2
```

## 10X Genomics data processing

```{r echo=FALSE, eval=TRUE}
seuratObj_TFH_global <- get(load("../output/seurat_pooled_sorted_unsorted_PBMC.rda"))
```

```{r echo=FALSE, eval=TRUE}
sorted_data <- seuratObj_TFH_global@raw.data[, 1:4500]
```

```{r}
common_genes <- intersect(colnames(data_build), rownames(sorted_data))
data_build_2 <- data_build[, match(common_genes, colnames(data_build))]
sorted_data_2 <- sorted_data[match(common_genes, rownames(sorted_data)),]
```

```{r}
pooled_data <- rbind(t(sorted_data_2), data_build_2)
```


## classtpx

We build the classifier now.

```{r echo=FALSE, eval=TRUE}
fac1 <- sapply(colnames(sorted_data), function(x) return(paste0(head(strsplit(x, "[_]")[[1]], -1), collapse="_")))
known_samples <- 1:4500
class_labs <- fac1
class_labs_2 <- factor(as.vector(mapvalues(class_labs, from = unique(class_labs), to = 1:length(unique(class_labs)))))
```

```{r}
topic_clus <- classtpx::class_topics(pooled_data, K=9, known_samples = known_samples, class_labs = class_labs_2, method = "theta.fix", shrink = FALSE, tol = 0.001, ord=FALSE)
save(topic_clus, file = "../output/classtpx_gtex_blood_sorted_immune_thresh.rda")
```


```{r echo=FALSE, eval=FALSE}
topic_clus <- classtpx::class_topics(pooled_data, K=11, known_samples = known_samples, class_labs = class_labs_2, method = "theta.fix", shrink = FALSE, tol = 100, ord=FALSE)
save(topic_clus, file = "../output/classtpx_gtex_blood_sorted_immune_thresh_2.rda")
```

## Cluster representation

```{r}
topic_clus <- get(load("../output/classtpx_gtex_blood_sorted_immune_thresh.rda"))
```

```{r echo=FALSE, eval=TRUE}
PlotCountClust <- function(topic_clus, fac){
  omega <- topic_clus$omega
  theta <- topic_clus$theta
  
  annotation <- data.frame(
    sample_id = paste0("X", 1:length(fac)),
    tissue_label = factor(fac,
                          levels = rev(unique(fac) ) ) );

  rownames(omega) <- annotation$sample_id;
  
  StructureGGplot(omega = omega,
                  annotation = annotation,
                  palette = c(RColorBrewer::brewer.pal(8, "Accent"), RColorBrewer::brewer.pal(8,"Set3")[c(1,3,4,5)]),
                  yaxis_label = "Types",
                  order_sample = TRUE,
                  axis_tick = list(axis_ticks_length = .1,
                                   axis_ticks_lwd_y = .1,
                                   axis_ticks_lwd_x = .1,
                                   axis_label_size = 7,
                                   axis_label_face = "bold"))
}
```

```{r echo=FALSE, eval=TRUE}
labs <- c(as.character(fac1), rep("Blood", 511))
PlotCountClust(topic_clus, labs)
```

```{r}
topic_clus_2 <- get(load("../output/classtpx_gtex_blood_sorted_immune_thresh_2.rda"))
```

```{r echo=FALSE, eval=TRUE}
labs <- c(as.character(fac1), rep("Blood", 511))
PlotCountClust(topic_clus_2, labs)
```


