---
title: "GTEx blood vessels + sorted immune cells"
author: "Kushal K Dey"
date: "9/1/2017"
output: html_document
---

We apply classtpx on the GTEx blood samples (bulk) with the sorted cells information obtained
from 10X Genomics.

## GTEx expression processing 

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(plyr)
library(classtpx)
library(CountClust)
library(maptpx)
library(ggplot2)
library(MAST)
library(GSEABase)
library(Seurat)
library(data.table)
```

```{r message = FALSE, warning=FALSE}
gtex_expr <- fread("../data/cis_gene_expression.txt")
```

```{r}
mat <- as.matrix(gtex_expr[, -(1:2)])
```

```{r}
samples_id <- read.table("../data/samples_id.txt")
tissue_names <- samples_id[,2]
table(tissue_names)
```

```{r}
idx1 <- which(tissue_names == "Blood")
mat2 <- mat[, idx1]
```


```{r}
gene_names <- as.character(read.table("../data/gene_names_GTEX_V6.txt")[,1])
gene_names_1 <- as.character(sapply(gene_names, function(x) return(strsplit(x, "[.]")[[1]][1])))
```

We convert these ensembl IDs to gene names.

```{r}
out <- mygene::queryMany(gene_names_1,  scopes="ensembl.gene", fields=c("symbol", "ensembl.gene"), species="human");
```
```{r}
idx2 <- match(out$query, gene_names_1)
gene_names_2 <- out$symbol[idx2]
```

```{r}
data_build <- t(mat2)
colnames(data_build) <- gene_names_2
```

## 10X Genomics data processing
