---
title: "singlecell-clustering"
output:
  html_document:
    toc: false
---

## Merkel Cell Carcinoma Data Study

We explore the clustering results using CountClust on the single cell RNA seq data to identify mechanism of Merkel Cell Carcinoma response and escape from T Cell Immunotherapy [PI: Aude Chapuis]. 

The data is obtained from a single MCPyV+-MCC patient with widely metastatic MCC, who was treated, and the treatment worked in the initial phase of one year, but then it relapsed. The single cell data was obtained using Drop-seq method from 10X Genomics. 10X-Genomics technology is uniquely poised to provide a detailed multidimensional view of the tumor microenvironment and cellular response. Key material from time points of response and progression including viable frozen single cell tumor digests (contain tumor & stroma & infiltrating immune cells), TIL cultures and PBMCs. 

Overall the data is collected over 4 time periods (August 2013, February 2015, February 2016 and October 2016). August 2013 is around the time of cancer detection, February 2015 is when the treatment is started, which is continued for one year, February 2016 is towards the end of the treatment period when the treatment is found to be working. Post this, the cancer relapses and October 2016 corresponds to a time period by which time the cancer has relapsed.

We consider the clustering of the single cells for each of the four time periods.

- [CountClust + tSNE analysis of scRNA-seq data from Aug 2013 - MCC1050](pbmc_MCC1050.html)

- [CountClust + tSNE analysis of scRNA-seq data from Feb 2015 - GRN0304](pbmc_GRN304.html)

- [CountClust + tSNE analysis of scRNA-seq data from Feb 2016 - GRN0535](pbmc_GRN535.html)

- [CountClust + tSNE analysis of scRNA-seq data from Oct 2016 - GRN0760](pbmc_GRN760.html)


We also pool the single cell data from the four time periods and perform the clustering.

- [CountClust + tSNE analysis of scRNA-seq data from all 4 time periods](aggregated_PBMC.html)

We perform Gene Set Enrichment Analysis (GSEA) of the cluster driving gene sets obtained from the cluster
model fits from each time period and also for aggregated data from 4 periods.

- [GSEA of CountClust clusters from Aug 2013 - MCC1050](gsea_MCC1050.html)

- [GSEA of CountClust clusters from Feb 2015 - GRN0304](gsea_GRN304.html)

- [GSEA of CountClust clusters from Feb 2016 - GRN0535](gsea_GRN535.html)

- [GSEA of CountClust clusters from Oct 2016 - GRN0760](gsea_GRN760.html)

- [GSEA of CountClust clusters from all 4 time periods](gsea_aggregated.html)


Based on the above studies, we note down the summary of the results obtained.


### Summary of the results from the analysis 


- A common pattern observed for each of the individual CountClust analysis done at each of the 4 time periods is that for $K=3$, one cluster seems to be driven by the myeloid markers like the S100* group, another by the hemoglobin expressed genes and finally a cluster that is driven by the cancer related genes. We however see the proportional representation of these clusters to vary from one time period to the other.

-  For higher order clusters, we sometimes get additional clusters to be driven by the cytotoxic T cell related genes (GZMA, GZMH) and NK cell related genes (NKG7). Also for further higher order clusters, PF4 or megakaryocyte gene related clusters are also observed. Plus, higher clusters also include clusters driven by CD74, CD79 and CD79A, which are markers for B cells. We also find a close connection of known markers for different cell types with the different higher order clusters we are observing (PF4, CD79A, CD74, S100A9, S100A8 etc). 

- For MCC1050, we find very low proportional representation of the hemoglobin related genes in the cells. This is at early stages of tumor progression before the T cells have been infused. Note that the samples at this stage are a combination of PBMCs, TILs and sc tumor digest. 

- For GRN304, we see a clearer separation of the clusters, and the hemoglobin related cluster seems to now occur in a handful of cells (much higher proportion compared to the first time). The samples at this stage are PBMCs.

- For GRN535, which is taken towards the end of the treatment period, we see a great reduction in the representation of the hemoglobin gene driven cluster. The myeloid cells cluster and the one driven by MALAT1, B2M dominate most tof the cells at this stage. It is known that radiation therapy can cause low levels of RBCs and WBCs resulting in low blood cell counts. That could be a possible reason why the hemoglobin genes are expressed in a small proportion of cells at this stage. The samples at this stage are PBMCs.

- During the final stage when the cancer has relapsed, we see the proportion of hemoglobin expressed genes has increased again. The samples at this stage are a combination of PBMCss, TILs and sc tumor digests.

- When we aggregate the data across the 4 time points, we fortunately do not see much bias due to batch effects resulting from cell collection and sequencing at these different time points. Because the data is clean, a lot of the features we see in the clusters in each of these time periods, is also visible for the pooled data across the 4 time periods.

- Even for the combined data, for $K=3$, the groups are similar to the individual time period data. For $K=6$, we get a cluster determined by CD79A, CD79B and CD74. This could be the B cell receptor cells. Also the 1st cluster seems to be driven by cancer related genes and markers for NK cells.Also, other clusters include myeloid lineage cells (S100*) and the hemoglobin related cells (likely RBCs).


- The GSEA analysis (done using [Consensus pathDB database](http://cpdb.molgen.mpg.de/)) seems to identify heme related pathways for the hemoglobin driving genes cluster and an immunity genes driven cluster for smaller clusters. But for larger clusters $K=6$, we do get clusters that are driven by T cell pathways, NK cell related pathways, toll like receptors and myeloid cell pathways and B cell pathways.


## HIV Data study

We next apply countClust and project the results on tSNE plot for three HIV+ and one HIV- patients. The single cell data were collected from Live cells and TF sorted cells. Also, for each case, the cells were obtained either from lymph node (LN) or from PBMCs. 

We first look at results from application of CountClust separately on the LN and PBMC data from Live cells
and TF sorted cells from each patient. 

- [CountClust + tSNE analysis of scRNA-seq data from LN and PBMC data in Live cells in TFH146](tsne_countclust_TFH146_Live.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN and PBMC data in Live cells in TFH041](tsne_countclust_TFH041_Live.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN and PBMC data in Live cells in TFH095](tsne_countclust_TFH095_Live.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN and PBMC data in Live cells in MP046](tsne_countclust_MP046_Live.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN and PBMC data in TF sorted cells in TFH146](tsne_countclust_TFH146_TF.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN and PBMC data in TF sorted cells in TFH041](tsne_countclust_TFH041_TF.html)


We next combine the LN and PBMC data and apply CountClust and visualize by tSNE the results.

First we do it for the Live cells

- [CountClust + tSNE analysis of scRNA-seq data from LN + PBMC data in Live cells in TFH095](tsne_countclust_TFH095_Live_pooled.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN + PBMC data in Live cells in TFH146](tsne_countclust_TFH146_Live_pooled.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN + PBMC data in Live cells in TFH041](tsne_countclust_TFH041_Live_pooled.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN + PBMC data in Live cells in MP046](tsne_countclust_MP046_Live_pooled.html)


Next we do the same for the TF sorted cells

- [CountClust + tSNE analysis of scRNA-seq data from LN + PBMC data in TF sorted cells in TFH146](tsne_countclust_TFH146_TF_pooled.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN + PBMC data in TF sorted cells in TFH041](tsne_countclust_TFH041_TF_pooled.html)

- [CountClust + tSNE analysis of scRNA-seq data from LN + PBMC data in TF sorted cells in MP046](tsne_countclust_MP046_TF_pooled.html)

We also check for the individual specific effects in driving the clusters by merging the TF sorted cells from two individuals together and then running CountClust on the merged data.

- [CountClust + tSNE analysis of scRNA-seq data from LN + PBMC data in TF sorted cells in TFH041+TFH146](tsne_countclust_TF_TFH041_TFH146.html)


We perform Gene Set Enrichment Analysis (GSEA) of the cluster driving gene sets obtained from the cluster
model fits in some of the studies above.

- [GSEA of the cluster driving gene sets in HIV studies](gsea_HIV.html)



### Summary of the results from the analysis 

- For TFH146, we find that in the LN cells, there is a cluster pattern driven by CD74 and other HLA related genes. The same is not observed for the PBMC cells, but the latter shows some clustering due to myeloid markers like S100*.

- For TFH095, in LN cells, we see the HLA driven cluster, as in TFH146. On the other hand for PBMCs, for $K=3$, we see a cluster driven by cytotoxic cells and NK cells and then a cluster that is driven by a mix of HLA and S100* genes. My feeling is that we will get a further split for higher $K$.

- So many HLA genes driven cluster was not observed for the cancer study as is in this case.

- For TF sorted cells in TFH146, no clear clustering pattern is observed from the t-sne plot in case of the LN cells and PBMC cells.

- For TF sorted cells in LN in TFH041, one cluster is dominated by HLA genes, anotherby CD3D, CCL5, CD48 etc.
These are the two clear clusters observed in this data.

- When we combine the LN and PBMC cells, the first distinct grouping is between the LN cells and the PBMC cells.

- In TFH095, for $K=3$, the three clusters are formed as follows - one by HLA genes, one by NK related genes, GZMA, GZMH, GNLY etc, and the third by markers like CD3D,CD2, CM1 etc

- Also when cells from two individuals are mixed (TF sorted cells in this case from TFH041 and TFH146), then the first clustering is at the level of the individual as checked by the last script.

- The GSEA analysis (done using [Consensus pathDB database](http://cpdb.molgen.mpg.de/)) of the clustering analysis of seprate CountClust application on LN and PBMC cells for Live cells or PBMC cells, seems to segregate for K=2 two clusters driven by APCs (antigen presenting cells) and T cells driven cluster, while ofr K=3, it seems to pick up NK cell related clusters in most cases.


## Exploration of the UMIs

The data in both the MCC and the HIV studies are UMI data. We checked for possible biases in the UMI assignment which would affect the counts of the UMIs and may require further normalization. We look first at how the number of UMIs assigned to a gene changes based on the properties of the gene - namely, the number of TSS, the GC content, the length of the gene etc. 

Previous studies tend to indicate that unlike the read counts, the UMI counts are stable with respect to the gene length. This is good for CountClust, as the latter does not notmalize the data by gene lengths and only performs the library size normalization. This would suggest that CountClust should adapt better in handling UMI data compared to non UMI data for single cell studies.

- [UMI study for TFH146](umi_study_TFH.html)

- [UMI versus Transcription Start Sites of the genes](umi_study_2.html)
 
- [UMI versus Transcript count and Transcript length of the genes](umi_study_3.html)

- [Dropout rates versus position of the genes along chromosome and pathway groups](dropout_study.html)

- [Dropout rates versus GC content of the genes](dropout_gc_study.html)

We next perform an analysis of the dispersion of genes against the average expression using Seurat and do a pathway based enrichment analysis of the genes that seem to be outliers in this plot.

- [Dispersion versus Average expression analysis](cvplot_analysis.html)

Finally, we have seen that usually there is a bias in the base composition of the UMIs that get added to the reads which are finally mapped. This seemed to be a big issue in the Fluidigm data we looked at before, but we wanted to check if they indeed play a role even for this data. The results summarized below suggest that the UMI bias is not appreciable for this data.

- [UMI base composition study : 10X Genomics vs Fluidigm](umi_composition.html)


Overall we did not see a relationship between the UMI patterns and the gene structure, we found very little compositional bias specially at the first few sites.



## 10X genomics PBMC(sorted + unsorted data)

We applied CountClust on the sorted immune cells data and unsorted PBMC data from 10X genomics. The results for the sorted cells alone study is the following

- [sorted immune cells CountClust study](sorted_cells_10X_analysis.html)

The results from applying countClust on just the unsorted PBMC data are 

- [unsorted PBMC cells CountClust study](pbmc_68k.html)

The results from applying CountClust on the sorted cells + unsorted PBMC cells is the 
following

- [CountClust study on sorted immune cells + unsorted PBMC cells](pooled_sorted_unsorted_pbmc_10X_analysis.html)

Since we have data available on sorted cells, and from the above analysis, merging the unsorted cells with the sorted ones seemed to preserve the biological structure, we decided to apply a supervised version of the Countclust method or grade of membership method and also pit it against a more standard classification algorithm like Support Vector Machines (SVM).

The results from a supervised Countclust model fit and a partially supervised model fits are presented below.

- [supervised Countclust study on sorted + unsorted PBMC cells](classification_gom.html)

- [partially supervised Countclust study on sorted + unsorted PBMC cells, allowing for 2 more clusters](classification_gom_2.html)

- [Comparison of SVM and Countclust results on sorted + unsorted PBMC data](svm_classtpx_comparison.html)

We show below that the training accuracy of the hard classification from classtpx is better than that of Support Vector Machines (SVM).

- [Training accuracy of classtpx and SVM on the sorted + unsorted PBMC data](train_accuracy_svm_classtpx.html)

We next threshold the genes based on the divergence measure of the sorted cell gene expression to pick out the strongest driving genes for classification. As of now, since the divrgence measure tends to subside to 0 inside of the first 100 genes, we pick 100 strongest genes per class and so, for the 9 sorted cell types, we have a total of 900 genes, on which the thresholded analysis is done. The results are presented below

- [Thresholded classtpx performance on sorted + unsorted PBMC data](thresholded_classtpx.html)

- [Training accuracy comparison of the original classtpx and the thresholded classtpx](train_accuracy_svm_classtpx_2.html)


We also trained the model on the sorted immune cells from 10X Genomics and then observed the
grades of memberships of the pooled MCC cells from the data on these classes. The results are presented below.

- [supervised CountClust study on the sorted immune cells + MCC cells pooled across 4 time points](classification_gom_MCC.html)




## Extras

The model for applying CountClust with covariates information is below

- [CountClust with covariate information : EM algorithm ](gom-cov.pdf)

The results of plotting the divergence measure $D$ for the *ExtractTopFeatures()* function in **CountClust** is the following

- [Divergence measure steepness study in CountClust](score_analysis_countclust.html)




