---
title: "Score analysis in ExtractTopFeatures in CountClust"
author: "Kushal K Dey"
date: "8/24/2017"
output: html_document
---

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(CountClust)
library(maptpx)
library(ggplot2)
library(MAST)
library(GSEABase)
library(Seurat)
```


## PBMC (sorted + unsorted) 68K data analysis

```{r}
topic_clus <- get(load("../output/10X_genomics_pooled_sort_unsort_maptpx.rda"))
```

### K=5

```{r}
out <- ExtractTopFeatures(topic_clus[[5]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r}
par(mfrow = c(3,3))
for(m in 1:5){
  plot(log(1:1000), log(scores[m,]+1), col="black", pch=20, ylab = "scores", xlab="top 100 genes (sorted)",
       main = paste0("cluster-", m))
}
```


### K=8

```{r}
out <- ExtractTopFeatures(topic_clus[[8]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r}
par(mfrow = c(3,3))
for(m in 1:8){
  plot(log(1:1000), log(scores[m,]+1), col="black", pch=20, ylab = "scores", xlab="top 100 genes (sorted)",
       main = paste0("cluster-", m))
}
```


### K=10

```{r}
out <- ExtractTopFeatures(topic_clus[[10]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r fig.height = 8}
par(mfrow = c(4,3))
for(m in 1:10){
  plot(log(1:1000), log(scores[m,]+1), col="black", pch=20, ylab = "scores", xlab="top 100 genes (sorted)",
       main = paste0("cluster-", m))
}
```


### QQplot  (K=8)

```{r}

out <- ExtractTopFeatures(topic_clus[[8]]$theta, top_features = 100, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores

ll <- vector(mode="list", length=dim(scores)[1])
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
  out <- qqnorm(log(scores[m,]+1), col="red", pch=20, cex = 1, main = paste0("QQplot: cluster - ", m))
  ll[[m]] <- cbind(out$x, (out$y - mean(out$y))/(sd(out$y)))
  qqline(log(scores[m,]+1))
}
```

```{r}
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
plot(density((ll[[m]][,1] - ll[[m]][,2])), col = "red", main = "density of distance between quantiles", xlab = "distance - qq", ylab = "density")
}
```

```{r}
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
plot((ll[[m]][,1] - ll[[m]][,2]), col = "red", main = "diff between quantiles", xlab = "index", ylab = "diff quantiles")
abline(0,0)
}
```

## PBMC 68K data analysis

```{r}
topic_clus <- get(load("../output/pbmc_68K_evan_maptpx.rda"))
```


### K=5

```{r}
out <- ExtractTopFeatures(topic_clus[[5]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r}
par(mfrow = c(3,3))
for(m in 1:5){
  plot(log(1:1000), log(scores[m,]+1), col="black", pch=20, ylab = "scores", xlab="top 100 genes (sorted)",
       main = paste0("cluster-", m))
}
```


### K=8

```{r}
out <- ExtractTopFeatures(topic_clus[[8]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r}
par(mfrow = c(3,3))
for(m in 1:8){
  plot(log(1:1000), log(scores[m,]+1), col="black", pch=20, ylab = "scores", xlab="top 100 genes (sorted)",
       main = paste0("cluster-", m))
}
```



### K=10

```{r}
out <- ExtractTopFeatures(topic_clus[[10]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r fig.height = 8}
par(mfrow = c(4, 3))
for(m in 1:10){
  plot(log(1:1000), log(scores[m,]+1), col="black", pch=20, ylab = "scores", xlab="top 100 genes (sorted)",
       main = paste0("cluster-", m))
}
```

### QQplot  (K=8)

```{r}

out <- ExtractTopFeatures(topic_clus[[8]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores

ll <- vector(mode="list", length=dim(scores)[1])
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
  out <- qqnorm(log(scores[m,]+1), col="red", pch=20, cex = 1, main = paste0("QQplot: cluster - ", m))
  ll[[m]] <- cbind(out$x, (out$y - mean(out$y))/(sd(out$y)))
  qqline(log(scores[m,]+1))
}
```

```{r}
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
plot(density((ll[[m]][,1] - ll[[m]][,2])), col = "red", main = "density of distance between quantiles", xlab = "distance - qq", ylab = "density")
}
```


```{r}
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
plot((ll[[m]][,1] - ll[[m]][,2]), col = "red", main = "diff between quantiles", xlab = "index", ylab = "diff quantiles")
abline(0,0)
}
```




## Aggregated MCC analysis

```{r echo=FALSE, eval=TRUE}
topic_clus <- get(load("../output/maptpx_aggregated_MCC.rda"))
```

### K=3

```{r}
out <- ExtractTopFeatures(topic_clus[[3]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r}
par(mfrow = c(2,2))
for(m in 1:3){
  plot(log(1:1000), log(scores[m,]+1), col="black", pch=20, ylab = "scores", xlab="top 100 genes (sorted)",
       main = paste0("cluster-", m))
}
```


### K=6

```{r}
out <- ExtractTopFeatures(topic_clus[[6]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r}
par(mfrow = c(3,2))
for(m in 1:6){
  plot(log(1:1000), log(scores[m,]+1), col="black", pch=20, ylab = "scores", xlab="top 100 genes (sorted)",
       main = paste0("cluster-", m))
}
```


### QQplot  (K=8)

```{r}

out <- ExtractTopFeatures(topic_clus[[8]]$theta, top_features = 1000, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
scores[is.na(scores)] <- 0
ll <- vector(mode="list", length=dim(scores)[1])
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
  out <- qqnorm(log(scores[m,]+1), col="red", pch=20, cex = 1, main = paste0("QQplot: cluster - ", m))
  ll[[m]] <- cbind(out$x, (out$y - mean(out$y, na.rm=TRUE))/(sd(out$y, na.rm=TRUE)))
  qqline(log(scores[m,]+1))
}
```

```{r}
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
plot(density((ll[[m]][,1] - ll[[m]][,2])), col = "red", main = "density of distance between quantiles", xlab = "distance - qq", ylab = "density")
}
```


```{r}
par(mfrow = c(3,3))
for(m in 1:dim(scores)[1]){
plot((ll[[m]][,1] - ll[[m]][,2]), col = "red", main = "diff between quantiles", xlab = "index", ylab = "diff quantiles")
abline(0,0)
}
```


