---
title: "Training accuracy of thresholded classtpx, regular classtpx and SVM"
author: "Kushal K Dey"
date: "8/29/2017"
output: html_document
---

## Finding threshold indices

```{r echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(plyr)
library(classtpx)
library(CountClust)
library(maptpx)
library(ggplot2)
library(MAST)
library(GSEABase)
library(Seurat)
```


```{r}
seuratObj_TFH_global <- get(load("../output/seurat_pooled_sorted_unsorted_PBMC.rda"))
```

```{r}
data <- seuratObj_TFH_global@raw.data[,1:4500]
```

```{r}
fac <- sapply(colnames(data), function(x) return(paste0(head(strsplit(x, "[_]")[[1]], -1), collapse="_")))
```

```{r}
counts_mat <- apply(data, 1, function(x) return(tapply(x, fac, sum)))
```

```{r}
counts_mat_prop <- t(apply(counts_mat, 1, function(x)
                         {
                           y <- (x+1e-07)
                           z <- y/sum(y)
                           return(z)
                          }))
```


```{r}
out <- ExtractTopFeatures(t(counts_mat_prop), top_features = 100, method = "poisson", options = "max")
indices <- out$indices
scores <- out$scores
```

```{r}
indices_vec <- as.vector(indices)
```

## Data Processing 

```{r echo=FALSE, eval=TRUE}
data <- seuratObj_TFH_global@raw.data
counts <- t(data)
```

```{r echo=FALSE, eval=TRUE}
fac1 <- sapply(colnames(data)[1:4500], function(x) return(paste0(head(strsplit(x, "[_]")[[1]], -1), collapse="_")))
class_labs <- fac1
```

```{r}
table(fac1)
```

## Subsampling rate : 0.25

```{r}
train_subsamples <- sample(1:4500, 1000, replace = FALSE)
table(class_labs[train_subsamples])
```

```{r}
class_labs_train <- class_labs[train_subsamples]
class_labs_test <- class_labs[-train_subsamples]
counts <- t(data[,1:4500])
known_samples <- train_subsamples
class_labs_train_2 <- factor(as.vector(plyr::mapvalues(class_labs_train, from = unique(class_labs), to = 1:length(unique(class_labs)))))
```

### classtpx application

```{r echo=FALSE, eval=TRUE}
topic_clus_1 <- classtpx::class_topics(counts, K=9, known_samples = known_samples, class_labs = class_labs_train_2, method = "theta.fix", shrink = FALSE, tol = 0.001, ord=FALSE)
save(topic_clus_1, file = "../output/classtpx_pbmc_68K_training_testing_1_nothresh.rda")
```


```{r echo=FALSE, eval=TRUE}
topic_clus_2 <- classtpx::class_topics(counts[,indices_vec], K=9, known_samples = known_samples, class_labs = class_labs_train_2, method = "theta.fix", shrink = FALSE, tol = 0.001, ord=FALSE)
save(topic_clus_2, file = "../output/classtpx_pbmc_68K_training_testing_1_thresh.rda")
```

```{r}
labels2 <- as.factor(apply(topic_clus_1$omega, 1, function(x) return(which.max(x))))
labels2_class <- unique(class_labs)[labels2]
length(which(labels2_class[-train_subsamples] != class_labs_test))/length(class_labs_test)
```

```{r}
labels2 <- as.factor(apply(topic_clus_2$omega, 1, function(x) return(which.max(x))))
labels2_class <- unique(class_labs)[labels2]
length(which(labels2_class[-train_subsamples] != class_labs_test))/length(class_labs_test)
```




## Subsampling rate : 0.5

```{r}
train_subsamples <- sample(1:4500, 2500, replace = FALSE)
table(class_labs[train_subsamples])
```

```{r}
class_labs_train <- class_labs[train_subsamples]
class_labs_test <- class_labs[-train_subsamples]
counts <- t(data[,1:4500])
known_samples <- train_subsamples
class_labs_train_2 <- factor(as.vector(plyr::mapvalues(class_labs_train, from = unique(class_labs), to = 1:length(unique(class_labs)))))
```

### classtpx application

```{r echo=FALSE, eval=TRUE}
topic_clus_1 <- classtpx::class_topics(counts, K=9, known_samples = known_samples, class_labs = class_labs_train_2, method = "theta.fix", shrink = FALSE, tol = 0.001, ord=FALSE)
save(topic_clus_1, file = "../output/classtpx_pbmc_68K_training_testing_2_nothresh.rda")
```


```{r echo=FALSE, eval=TRUE}
topic_clus_2 <- classtpx::class_topics(counts[,indices_vec], K=9, known_samples = known_samples, class_labs = class_labs_train_2, method = "theta.fix", shrink = FALSE, tol = 0.001, ord=FALSE)
save(topic_clus_2, file = "../output/classtpx_pbmc_68K_training_testing_2_thresh.rda")
```

```{r}
labels2 <- as.factor(apply(topic_clus_1$omega, 1, function(x) return(which.max(x))))
labels2_class <- unique(class_labs)[labels2]
length(which(labels2_class[-train_subsamples] != class_labs_test))/length(class_labs_test)
```

```{r}
labels2 <- as.factor(apply(topic_clus_2$omega, 1, function(x) return(which.max(x))))
labels2_class <- unique(class_labs)[labels2]
length(which(labels2_class[-train_subsamples] != class_labs_test))/length(class_labs_test)
```



## Subsampling rate : 0.75

```{r}
train_subsamples <- sample(1:4500, 3500, replace = FALSE)
table(class_labs[train_subsamples])
```

```{r}
class_labs_train <- class_labs[train_subsamples]
class_labs_test <- class_labs[-train_subsamples]
counts <- t(data[,1:4500])
known_samples <- train_subsamples
class_labs_train_2 <- factor(as.vector(plyr::mapvalues(class_labs_train, from = unique(class_labs), to = 1:length(unique(class_labs)))))
```

### classtpx application

```{r echo=FALSE, eval=TRUE}
topic_clus_1 <- classtpx::class_topics(counts, K=9, known_samples = known_samples, class_labs = class_labs_train_2, method = "theta.fix", shrink = FALSE, tol = 0.001, ord=FALSE)
save(topic_clus_1, file = "../output/classtpx_pbmc_68K_training_testing_3_nothresh.rda")
```


```{r echo=FALSE, eval=TRUE}
topic_clus_2 <- classtpx::class_topics(counts[,indices_vec], K=9, known_samples = known_samples, class_labs = class_labs_train_2, method = "theta.fix", shrink = FALSE, tol = 0.001, ord=FALSE)
save(topic_clus_2, file = "../output/classtpx_pbmc_68K_training_testing_3_thresh.rda")
```

```{r}
labels2 <- as.factor(apply(topic_clus_1$omega, 1, function(x) return(which.max(x))))
labels2_class <- unique(class_labs)[labels2]
length(which(labels2_class[-train_subsamples] != class_labs_test))/length(class_labs_test)
```

```{r}
labels2 <- as.factor(apply(topic_clus_2$omega, 1, function(x) return(which.max(x))))
labels2_class <- unique(class_labs)[labels2]
length(which(labels2_class[-train_subsamples] != class_labs_test))/length(class_labs_test)
```

